# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: true
    style: silent

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: false

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: new_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: camel_case

  NestingDepth:
    enabled: true
    max_depth: 5
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    enabled: true
    ignore_unspecified: true
    min_properties: 2
    separate_groups: true
    order:
      - composes
      -
      - align-content
      - align-items
      - align-self
      - alignment-adjust
      - alignment-baseline
      - all
      - animation
      - animation-delay
      - animation-direction
      - animation-duration
      - animation-fill-mode
      - animation-iteration-count
      - animation-name
      - animation-play-state
      - animation-timing-function
      - app-region
      - appearance
      - aspect-ratio
      - backdrop-filter
      - backface-visibility
      - background
      - background-attachment
      - background-blend-mode
      - background-clip
      - background-color
      - background-composite
      - background-image
      - background-origin
      - background-position
      - background-position-x
      - background-position-y
      - background-repeat
      - background-repeat-x
      - background-repeat-y
      - background-size
      - baseline-shift
      - block-size
      - bookmark-label
      - bookmark-level
      - bookmark-target
      - border
      - border-after
      - border-after-color
      - border-after-style
      - border-after-width
      - border-before
      - border-before-color
      - border-before-style
      - border-before-width
      - border-block-end
      - border-block-end-color
      - border-block-end-style
      - border-block-end-width
      - border-block-start
      - border-block-start-color
      - border-block-start-style
      - border-block-start-width
      - border-bottom
      - border-bottom-color
      - border-bottom-left-radius
      - border-bottom-right-radius
      - border-bottom-style
      - border-bottom-width
      - border-collapse
      - border-color
      - border-end
      - border-end-color
      - border-end-style
      - border-end-width
      - border-fit
      - border-horizontal-spacing
      - border-image
      - border-image-outset
      - border-image-repeat
      - border-image-slice
      - border-image-source
      - border-image-width
      - border-inline-end
      - border-inline-end-color
      - border-inline-end-style
      - border-inline-end-width
      - border-inline-start
      - border-inline-start-color
      - border-inline-start-style
      - border-inline-start-width
      - border-left
      - border-left-color
      - border-left-style
      - border-left-width
      - border-radius
      - border-right
      - border-right-color
      - border-right-style
      - border-right-width
      - border-spacing
      - border-start
      - border-start-color
      - border-start-style
      - border-start-width
      - border-style
      - border-top
      - border-top-color
      - border-top-left-radius
      - border-top-right-radius
      - border-top-style
      - border-top-width
      - border-vertical-spacing
      - border-width
      - bottom
      - box-align
      - box-decoration-break
      - box-direction
      - box-flex
      - box-flex-group
      - box-lines
      - box-ordinal-group
      - box-orient
      - box-pack
      - box-reflect
      - box-shadow
      - box-sizing
      - break-after
      - break-before
      - break-inside
      - buffered-rendering
      - caption-side
      - clear
      - clip
      - clip-path
      - clip-rule
      - color
      - color-interpolation
      - color-interpolation-filters
      - color-profile
      - color-rendering
      - column-axis
      - column-break-after
      - column-break-before
      - column-break-inside
      - column-count
      - column-fill
      - column-gap
      - column-progression
      - column-rule
      - column-rule-color
      - column-rule-style
      - column-rule-width
      - column-span
      - column-width
      - columns
      - contain
      - content
      - counter-increment
      - counter-reset
      - crop
      - cursor
      - direction
      - display
      - dominant-baseline
      - drop-initial-after-adjust
      - drop-initial-after-align
      - drop-initial-before-adjust
      - drop-initial-before-align
      - drop-initial-size
      - drop-initial-value
      - empty-cells
      - enable-background
      - fill
      - fill-opacity
      - fill-rule
      - filter
      - fit
      - fit-position
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - float
      - float-offset
      - flood-color
      - flood-opacity
      - flow-from
      - flow-into
      - font
      - font-family
      - font-feature-settings
      - font-kerning
      - font-size
      - font-size-adjust
      - font-size-delta
      - font-smoothing
      - font-stretch
      - font-style
      - font-variant
      - font-variant-ligatures
      - font-weight
      - glyph-orientation-horizontal
      - glyph-orientation-vertical
      - grid
      - grid-after
      - grid-area
      - grid-auto-columns
      - grid-auto-flow
      - grid-auto-rows
      - grid-before
      - grid-column
      - grid-columns
      - grid-end
      - grid-row
      - grid-rows
      - grid-start
      - grid-template
      - grid-template-areas
      - hanging-punctuation
      - height
      - highlight
      - hyphenate-after
      - hyphenate-before
      - hyphenate-character
      - hyphenate-limit-after
      - hyphenate-limit-before
      - hyphenate-limit-lines
      - hyphenate-lines
      - hyphenate-resource
      - hyphens
      - icon
      - image-orientation
      - image-rendering
      - image-resolution
      - inline-box-align
      - inline-size
      - isolation
      - justify-content
      - justify-self
      - kerning
      - left
      - letter-spacing
      - lighting-color
      - line-align
      - line-box-contain
      - line-break
      - line-clamp
      - line-grid
      - line-height
      - line-snap
      - line-stacking
      - line-stacking-ruby
      - line-stacking-shift
      - line-stacking-strategy
      - list-style
      - list-style-image
      - list-style-position
      - list-style-type
      - locale
      - logical-height
      - logical-width
      - margin
      - margin-after
      - margin-after-collapse
      - margin-before
      - margin-before-collapse
      - margin-block-end
      - margin-block-start
      - margin-bottom
      - margin-bottom-collapse
      - margin-collapse
      - margin-end
      - margin-inline-end
      - margin-inline-start
      - margin-left
      - margin-right
      - margin-start
      - margin-top
      - margin-top-collapse
      - mark
      - mark-after
      - mark-before
      - marker
      - marker-end
      - marker-mid
      - marker-start
      - marks
      - marquee
      - marquee-direction
      - marquee-increment
      - marquee-play-count
      - marquee-repetition
      - marquee-speed
      - marquee-style
      - mask
      - mask-box-image
      - mask-box-image-outset
      - mask-box-image-repeat
      - mask-box-image-slice
      - mask-box-image-source
      - mask-box-image-width
      - mask-clip
      - mask-composite
      - mask-image
      - mask-origin
      - mask-position
      - mask-position-x
      - mask-position-y
      - mask-repeat
      - mask-repeat-x
      - mask-repeat-y
      - mask-size
      - mask-source-type
      - mask-type
      - max-block-size
      - max-height
      - max-inline-size
      - max-logical-height
      - max-logical-width
      - max-width
      - max-zoom
      - min-block-size
      - min-height
      - min-inline-size
      - min-logical-height
      - min-logical-width
      - min-width
      - min-zoom
      - mix-blend-mode
      - move-to
      - nav-down
      - nav-index
      - nav-left
      - nav-right
      - nav-up
      - object-fit
      - object-position
      - offset-block-end
      - offset-block-start
      - offset-inline-end
      - offset-inline-start
      - opacity
      - order
      - orientation
      - orphans
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      - overflow
      - overflow-style
      - overflow-wrap
      - overflow-x
      - overflow-y
      - padding
      - padding-after
      - padding-before
      - padding-block-end
      - padding-block-start
      - padding-bottom
      - padding-end
      - padding-inline-end
      - padding-inline-start
      - padding-left
      - padding-right
      - padding-start
      - padding-top
      - page
      - page-break-after
      - page-break-before
      - page-break-inside
      - page-policy
      - paint-order
      - perspective
      - perspective-origin
      - perspective-origin-x
      - perspective-origin-y
      - phonemes
      - pointer-events
      - position
      - print-color-adjust
      - punctuation-trim
      - quotes
      - region-break-after
      - region-break-before
      - region-break-inside
      - region-overflow
      - rendering-intent
      - resize
      - rest
      - rest-after
      - rest-before
      - right
      - rotation
      - rotation-point
      - rtl-ordering
      - ruby-align
      - ruby-overhang
      - ruby-position
      - ruby-span
      - scroll-behavior
      - shape-image-threshold
      - shape-inside
      - shape-margin
      - shape-outside
      - shape-padding
      - shape-rendering
      - size
      - speak
      - src
      - stop-color
      - stop-opacity
      - string-set
      - stroke
      - stroke-dasharray
      - stroke-dashoffset
      - stroke-linecap
      - stroke-linejoin
      - stroke-miterlimit
      - stroke-opacity
      - stroke-width
      - svg-shadow
      - tab-size
      - table-layout
      - tap-highlight-color
      - target
      - target-name
      - target-new
      - target-position
      - text-align
      - text-align-last
      - text-anchor
      - text-combine
      - text-decoration
      - text-decoration-color
      - text-decoration-line
      - text-decoration-style
      - text-decorations-in-effect
      - text-emphasis
      - text-emphasis-color
      - text-emphasis-position
      - text-emphasis-style
      - text-fill-color
      - text-height
      - text-indent
      - text-justify
      - text-line-through-color
      - text-line-through-mode
      - text-line-through-style
      - text-line-through-width
      - text-orientation
      - text-outline
      - text-overflow
      - text-overline-color
      - text-overline-mode
      - text-overline-style
      - text-overline-width
      - text-rendering
      - text-security
      - text-shadow
      - text-size-adjust
      - text-stroke
      - text-stroke-color
      - text-stroke-width
      - text-transform
      - text-underline-color
      - text-underline-mode
      - text-underline-position
      - text-underline-style
      - text-underline-width
      - text-wrap
      - top
      - touch-action
      - touch-action-delay
      - transform
      - transform-origin
      - transform-origin-x
      - transform-origin-y
      - transform-origin-z
      - transform-style
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      - unicode-bidi
      - unicode-range
      - user-drag
      - user-modify
      - user-select
      - user-zoom
      - vector-effect
      - vertical-align
      - visibility
      - voice-balance
      - voice-duration
      - voice-pitch
      - voice-pitch-range
      - voice-rate
      - voice-stress
      - voice-volume
      - white-space
      - widows
      - width
      - will-change
      - word-break
      - word-spacing
      - word-wrap
      - wrap-flow
      - wrap-through
      - writing-mode
      - z-index
      - zoom

  PropertySpelling:
    enabled: true
    extra_properties: [
    'composes'
    ]
    disabled_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 5

  SelectorFormat:
    enabled: true
    convention: camel_case

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: false
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterComment:
    enabled: false
    style: one_space # or 'no_space', or 'at_least_one_space'
    allow_empty_comments: true

  SpaceAfterPropertyColon:
    enabled: false
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: false
    style: one_space # or 'no_space', 'at_least_one_space' or 'one_space_or_newline'

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: false

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
